---
- block:
    - name: homebrew cask upgrade
      environment:
        HOMEBREW_CASK_OPTS: --appdir=/Applications
      homebrew_cask:
        upgrade_all: true
        # Do not upgrade auto-updating casks implicitly. They may update outside
        # Homebrew and can require interactive authentication or app restarts.
        greedy: false

    - name: homebrew cask install
      environment:
        HOMEBREW_CASK_OPTS: --appdir=/Applications
      homebrew_cask:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      with_items: "{{ packages }}"

  tags:
    - homebrew_cask
